#!/bin/bash

BASE_DIR=${BASE_DIR:-"$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"}
cd $BASE_DIR

export LD_PRELOAD=/home/IAL/mtnk/work/nccl_2.7.8-1+cuda10.2_x86_64/lib/libnccl.so
RL=${BASE_DIR}/rl
echo $RL

echo "JOB_ID=${PBS_JOBID}"
echo "conda env=${CONDA_ENV}"

NP=${NP:-8}
MODEL=${MODEL:-resnet18}
BATCH_SIZE=${BATCH_SIZE:-256}
TIMESTAMP=${TIMESTAMP:-0}

CONSOLIDATE_GRADS=${CONSOLIDATE_GRADS:-false}
SKIP_GRAD_SCALING=${SKIP_GRAD_SCALING:-false}

DECOMPOSER=${DECOMPOSER:-ml_part}
SAVE_DEPLOYMENT=${SAVE_DEPLOYMENT:-true}
LOAD_DEPLOYMENT=${LOAD_DEPLOYMENT:-false}
SAVE_GRAPH_PROFILE=${SAVE_GRAPH_PROFILE:-false}
LOAD_GRAPH_PROFILE=${LOAD_GRAPH_PROFILE:-false}

MIN_PIPELINE=${MIN_PIPELINE:-1}
MAX_PIPELINE=${MAX_PIPELINE:-32}
MAX_PARTITION_NUM=${MAX_PARTITION_NUM:-30}
MEM_MARGIN=${MEM_MARGIN:-0.1}

PROF_CACHE_DIR=${HOME}/.rannc/cache
mkdir -p ${PROF_CACHE_DIR}
DEPLOYMENT_FILE=${DEPLOYMENT_FILE:-"${PROF_CACHE_DIR}/prof_deployment_${PARAMS}.bin"}
GRAPH_PROFILE_FILE=${GRAPH_PROFILE_FILE:-"${PROF_CACHE_DIR}/graph_profile_${PARAMS}.bin"}


PARAMS="NP${NP}_M${MODEL}_T${TIMESTAMP}"

export LC_CTYPE=ja_JP.UTF-8 LC_COLLATE=ja_JP.UTF-8 LC_TIME=ja_JP.UTF-8 LC_NUMERIC=ja_JP.UTF-8 LC_MONETARY=ja_JP.UTF-8

MPI_OPTS="-np ${NP}"
MPI_OPTS+=" --tag-output"
MPI_OPTS+=" -bind-to none -map-by slot"
MPI_OPTS+=" --mca pml ucx --mca btl ^vader,tcp,openib"
MPI_OPTS+=" -x PATH -x LD_LIBRARY_PATH -x LD_PRELOAD"
MPI_OPTS+=" -x UCX_MEMTYPE_CACHE=n -x UCX_NET_DEVICES=mlx5_2:1"
MPI_OPTS+=" -x NCCL_DEBUG=WARNING -x NCCL_IB_HCA=mlx5_2"
MPI_OPTS+=" -x RANNC_DO_UNCOARSENING=false"
MPI_OPTS+=" -x RANNC_MIN_PIPELINE=${MIN_PIPELINE}"
MPI_OPTS+=" -x RANNC_MAX_PIPELINE=${MAX_PIPELINE}"
MPI_OPTS+=" -x RANNC_MEM_MARGIN=${MEM_MARGIN}"
MPI_OPTS+=" -x RANNC_SAVE_DEPLOYMENT=${SAVE_DEPLOYMENT}"
MPI_OPTS+=" -x RANNC_LOAD_DEPLOYMENT=${LOAD_DEPLOYMENT}"
MPI_OPTS+=" -x RANNC_DEPLOYMENT_FILE=${DEPLOYMENT_FILE}"
MPI_OPTS+=" -x RANNC_SAVE_GRAPH_PROFILE=${SAVE_GRAPH_PROFILE}"
MPI_OPTS+=" -x RANNC_LOAD_GRAPH_PROFILE=${LOAD_GRAPH_PROFILE}"
MPI_OPTS+=" -x RANNC_GRAPH_PROFILE_FILE=${GRAPH_PROFILE_FILE}"
MPI_OPTS+=" -x RANNC_CONSOLIDATE_GRADS=${CONSOLIDATE_GRADS}"
MPI_OPTS+=" -x RANNC_SKIP_GRAD_SCALING=${SKIP_GRAD_SCALING}"

RL_OPTS="${RL}"
RL_OPTS+=" $(uname -n)"
RL_OPTS+=" 20010"

DIST_URL="tcp://$(uname -n):20011"

mpirun ${MPI_OPTS} \
       ${RL_OPTS} \
  main_rannc.py \
  --dist-url ${DIST_URL} --dist-backend 'nccl' \
  -a ${MODEL} \
  --batch-size ${BATCH_SIZE} \
  --epochs 10 \
  /share01/mtnk/work/imagenet/pytorch_small
exit
